#############################################################################################################################################################################################################
#############################################################################################################################################################################################################
### 把 kong_model2 加入 sys.path
import os
code_exe_path = os.path.realpath(__file__)                   ### 目前執行 step10_b.py 的 path
code_exe_path_element = code_exe_path.split("\\")            ### 把 path 切分 等等 要找出 kong_model 在第幾層
kong_layer = code_exe_path_element.index("kong_model2")      ### 找出 kong_model2 在第幾層
kong_model2_dir = "\\".join(code_exe_path_element[:kong_layer + 1])  ### 定位出 kong_model2 的 dir
import sys                                                   ### 把 kong_model2 加入 sys.path
sys.path.append(kong_model2_dir)
# print(__file__.split("\\")[-1])
# print("    code_exe_path:", code_exe_path)
# print("    code_exe_path_element:", code_exe_path_element)
# print("    kong_layer:", kong_layer)
# print("    kong_model2_dir:", kong_model2_dir)
#############################################################################################################################################################################################################
kong_to_py_layer = len(code_exe_path_element) - 1 - kong_layer  ### 中間 -1 是為了長度轉index
# print("    kong_to_py_layer:", kong_to_py_layer)
if  (kong_to_py_layer == 0): template_dir = ""
elif(kong_to_py_layer == 2): template_dir = code_exe_path_element[kong_layer + 1][0:]  ### [7:] 是為了去掉 step1x_， 後來覺得好像改有意義的名字不去掉也行所以 改 0
elif(kong_to_py_layer == 3): template_dir = code_exe_path_element[kong_layer + 1][0:] + "/" + code_exe_path_element[kong_layer + 2][0:]  ### [5:] 是為了去掉 mask_ ，前面的 mask_ 是為了python 的 module 不能 數字開頭， 隨便加的這樣子， 後來覺得 自動排的順序也可以接受， 所以 改0
elif(kong_to_py_layer >  3): template_dir = code_exe_path_element[kong_layer + 1][0:] + "/" + code_exe_path_element[kong_layer + 2][0:] + "/" + "/".join(code_exe_path_element[kong_layer + 3: -1])
# print("    template_dir:", template_dir)  ### 舉例： template_dir: 7_mask_unet/5_os_book_and_paper_have_dtd_hdr_mix_bg_tv_s04_mae
#############################################################################################################################################################################################################
exp_dir = template_dir
#############################################################################################################################################################################################################

from step06_a_datas_obj import *
from step10_a2_loss_info_obj import *
from step10_b2_exp_builder import Exp_builder

rm_paths = [path for path in sys.path if code_dir in path]
for rm_path in rm_paths: sys.path.remove(rm_path)
rm_moduless = [module for module in sys.modules if "step09" in module]
for rm_module in rm_moduless: del sys.modules[rm_module]


import Exps_8_multi_unet.I_w_Mgt_to_Wx_Wy_Wz_try_mul_M_focus .a_normal .step10_a as I_to_Wxyz_exp_builder
import Exps_8_multi_unet.I_w_Mgt_to_Wx_Wy_Wz_try_mul_M_focus .b_limit  .step10_a as I_to_Wxyz_limit_exp_builder
import Exps_8_multi_unet.W_w_Mgt_to_Cx_Cy_try_mul_M_focus    .a_normal .step10_a as W_to_Cxy_exp_builder
import Exps_8_multi_unet.W_w_Mgt_to_Cx_Cy_try_mul_M_focus    .b_limit  .step10_a as W_to_Cxy_limit_exp_builder
#############################################################################################################################################################################################################
'''
exp_dir 是 決定 result_dir 的 "上一層"資料夾 名字喔！ exp_dir要巢狀也沒問題～
比如：exp_dir = "6_mask_unet/自己命的名字"，那 result_dir 就都在：
    6_mask_unet/自己命的名字/result_a
    6_mask_unet/自己命的名字/result_b
    6_mask_unet/自己命的名字/...
'''
''' I_to_Wxyz 固定， 變動 W_to_Cxy '''
from step09 import *
Reload_from_which_Exp = I_to_Wxyz_exp_builder.L5_ch032
###############################################################################################################################
use_db_obj = type8_blender_dis_wc_flow_try_mul_M
use_loss_obj = [G_mae_s001_loss_info_builder.set_loss_target("UNet_z").copy(), G_mae_s001_loss_info_builder.set_loss_target("UNet_y").copy(), G_mae_s001_loss_info_builder.set_loss_target("UNet_x").copy(), G_mae_s001_loss_info_builder.set_loss_target("UNet_Cx").copy(), G_mae_s001_loss_info_builder.set_loss_target("UNet_Cy").copy()]  ### z, y, x 順序是看 step07_b_0b_Multi_UNet 來對應的喔

#############################################################
L2_ch128 = Exp_builder().set_basic("train", use_db_obj, block1_L2_ch128_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L2_ch128_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L2_ch128).set_result_name(result_name="I_to_Cxy_L2_ch128-no_time")
L2_ch064 = Exp_builder().set_basic("train", use_db_obj, block1_L2_ch064_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L2_ch064_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L2_ch064).set_result_name(result_name="I_to_Cxy_L2_ch064-no_time")
L2_ch032 = Exp_builder().set_basic("train", use_db_obj, block1_L2_ch032_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L2_ch032_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L2_ch032).set_result_name(result_name="I_to_Cxy_L2_ch032-no_time")
L2_ch016 = Exp_builder().set_basic("train", use_db_obj, block1_L2_ch016_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L2_ch016_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L2_ch016).set_result_name(result_name="I_to_Cxy_L2_ch016-no_time")
L2_ch008 = Exp_builder().set_basic("train", use_db_obj, block1_L2_ch008_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L2_ch008_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L2_ch008).set_result_name(result_name="I_to_Cxy_L2_ch008-no_time")
L2_ch004 = Exp_builder().set_basic("train", use_db_obj, block1_L2_ch004_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L2_ch004_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L2_ch004).set_result_name(result_name="I_to_Cxy_L2_ch004-no_time")
L2_ch002 = Exp_builder().set_basic("train", use_db_obj, block1_L2_ch002_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L2_ch002_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L2_ch002).set_result_name(result_name="I_to_Cxy_L2_ch002-no_time")
L2_ch001 = Exp_builder().set_basic("train", use_db_obj, block1_L2_ch001_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L2_ch001_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L2_ch001).set_result_name(result_name="I_to_Cxy_L2_ch001-no_time")

L3_ch128 = Exp_builder().set_basic("train", use_db_obj, block1_L3_ch128_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L3_ch128_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L3_ch128).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L3_ch128_block1_&&_I_to_Cy_L3_ch128_block1-20220121_110933")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L3_ch064 = Exp_builder().set_basic("train", use_db_obj, block1_L3_ch064_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L3_ch064_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L3_ch064).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L3_ch064_block1_&&_I_to_Cy_L3_ch064_block1-20220121_042325")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L3_ch032 = Exp_builder().set_basic("train", use_db_obj, block1_L3_ch032_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L3_ch032_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L3_ch032).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L3_ch032_block1_&&_I_to_Cy_L3_ch032_block1-20220121_011215")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L3_ch016 = Exp_builder().set_basic("train", use_db_obj, block1_L3_ch016_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L3_ch016_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L3_ch016).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L3_ch016_block1_&&_I_to_Cy_L3_ch016_block1-20220120_145509")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L3_ch008 = Exp_builder().set_basic("train", use_db_obj, block1_L3_ch008_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L3_ch008_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L3_ch008).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L3_ch008_block1_&&_I_to_Cy_L3_ch008_block1-20220120_174041")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L3_ch004 = Exp_builder().set_basic("train", use_db_obj, block1_L3_ch004_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L3_ch004_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L3_ch004).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L3_ch004_block1_&&_I_to_Cy_L3_ch004_block1-20220120_201548")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L3_ch002 = Exp_builder().set_basic("train", use_db_obj, block1_L3_ch002_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L3_ch002_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L3_ch002).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L3_ch002_block1_&&_I_to_Cy_L3_ch002_block1-20220120_224526")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L3_ch001 = Exp_builder().set_basic("train", use_db_obj, block1_L3_ch001_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L3_ch001_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L3_ch001).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L3_ch001_block1_&&_I_to_Cy_L3_ch001_block1-20220121_084400")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)

L4_ch128 = Exp_builder().set_basic("train", use_db_obj, block1_L4_ch128_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L4_ch128_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L4_ch128).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L4_ch128_block1_&&_I_to_Cy_L4_ch128_block1-20220121_073642")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L4_ch064 = Exp_builder().set_basic("train", use_db_obj, block1_L4_ch064_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L4_ch064_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L4_ch064).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L4_ch064_block1_&&_I_to_Cy_L4_ch064_block1-20220121_014955")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L4_ch032 = Exp_builder().set_basic("train", use_db_obj, block1_L4_ch032_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L4_ch032_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L4_ch032).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L4_ch032_block1_&&_I_to_Cy_L4_ch032_block1-20220120_231132")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L4_ch016 = Exp_builder().set_basic("train", use_db_obj, block1_L4_ch016_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L4_ch016_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L4_ch016).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L4_ch016_block1_&&_I_to_Cy_L4_ch016_block1-20220120_145610")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L4_ch008 = Exp_builder().set_basic("train", use_db_obj, block1_L4_ch008_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L4_ch008_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L4_ch008).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L4_ch008_block1_&&_I_to_Cy_L4_ch008_block1-20220120_171025")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L4_ch004 = Exp_builder().set_basic("train", use_db_obj, block1_L4_ch004_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L4_ch004_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L4_ch004).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L4_ch004_block1_&&_I_to_Cy_L4_ch004_block1-20220120_191509")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L4_ch002 = Exp_builder().set_basic("train", use_db_obj, block1_L4_ch002_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L4_ch002_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L4_ch002).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L4_ch002_block1_&&_I_to_Cy_L4_ch002_block1-20220120_211428")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L4_ch001 = Exp_builder().set_basic("train", use_db_obj, block1_L4_ch001_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L4_ch001_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L4_ch001).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L4_ch001_block1_&&_I_to_Cy_L4_ch001_block1-20220121_054039")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)

L5_ch128 = Exp_builder().set_basic("train", use_db_obj, block1_L5_ch128_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L5_ch128_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L5_ch128).set_result_name(result_name="I_to_Cxy_L5_ch128-no_time")  ### 訓練超出 GPU記憶體
L5_ch064 = Exp_builder().set_basic("train", use_db_obj, block1_L5_ch064_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L5_ch064_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L5_ch064).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L5_ch064_block1_&&_I_to_Cy_L5_ch064_block1-20220121_030726")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L5_ch032 = Exp_builder().set_basic("train", use_db_obj, block1_L5_ch032_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L5_ch032_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L5_ch032).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L5_ch032_block1_&&_I_to_Cy_L5_ch032_block1-20220121_001247")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L5_ch016 = Exp_builder().set_basic("train", use_db_obj, block1_L5_ch016_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L5_ch016_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L5_ch016).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L5_ch016_block1_&&_I_to_Cy_L5_ch016_block1-20220120_153932")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L5_ch008 = Exp_builder().set_basic("train", use_db_obj, block1_L5_ch008_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L5_ch008_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L5_ch008).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L5_ch008_block1_&&_I_to_Cy_L5_ch008_block1-20220120_180029")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L5_ch004 = Exp_builder().set_basic("train", use_db_obj, block1_L5_ch004_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L5_ch004_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L5_ch004).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L5_ch004_block1_&&_I_to_Cy_L5_ch004_block1-20220120_200902")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L5_ch002 = Exp_builder().set_basic("train", use_db_obj, block1_L5_ch002_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L5_ch002_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L5_ch002).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L5_ch002_block1_&&_I_to_Cy_L5_ch002_block1-20220120_221153")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L5_ch001 = Exp_builder().set_basic("train", use_db_obj, block1_L5_ch001_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L5_ch001_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L5_ch001).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L5_ch001_block1_&&_I_to_Cy_L5_ch001_block1-20220121_080334")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)

L6_ch064 = Exp_builder().set_basic("train", use_db_obj, block1_L6_ch064_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L6_ch064_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L6_ch064).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L6_ch064_block1_&&_I_to_Cy_L6_ch064_block1-20220121_091407")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L6_ch032 = Exp_builder().set_basic("train", use_db_obj, block1_L6_ch032_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L6_ch032_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L6_ch032).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L6_ch032_block1_&&_I_to_Cy_L6_ch032_block1-20220121_031804")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L6_ch016 = Exp_builder().set_basic("train", use_db_obj, block1_L6_ch016_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L6_ch016_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L6_ch016).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L6_ch016_block1_&&_I_to_Cy_L6_ch016_block1-20220120_223524")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L6_ch008 = Exp_builder().set_basic("train", use_db_obj, block1_L6_ch008_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L6_ch008_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L6_ch008).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L6_ch008_block1_&&_I_to_Cy_L6_ch008_block1-20220120_201824")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L6_ch004 = Exp_builder().set_basic("train", use_db_obj, block1_L6_ch004_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L6_ch004_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L6_ch004).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L6_ch004_block1_&&_I_to_Cy_L6_ch004_block1-20220120_180815")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L6_ch002 = Exp_builder().set_basic("train", use_db_obj, block1_L6_ch002_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L6_ch002_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L6_ch002).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L6_ch002_block1_&&_I_to_Cy_L6_ch002_block1-20220121_011146")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L6_ch001 = Exp_builder().set_basic("train", use_db_obj, block1_L6_ch001_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L6_ch001_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L6_ch001).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L6_ch001_block1_&&_I_to_Cy_L6_ch001_block1-20220121_070936")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)

L7_ch032 = Exp_builder().set_basic("train", use_db_obj, block1_L7_ch032_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L7_ch032_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L7_ch032).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L7_ch032_block1_&&_I_to_Cy_L7_ch032_block1-20220121_064536")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L7_ch016 = Exp_builder().set_basic("train", use_db_obj, block1_L7_ch016_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L7_ch016_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L7_ch016).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L7_ch016_block1_&&_I_to_Cy_L7_ch016_block1-20220121_013103")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L7_ch008 = Exp_builder().set_basic("train", use_db_obj, block1_L7_ch008_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L7_ch008_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L7_ch008).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L7_ch008_block1_&&_I_to_Cy_L7_ch008_block1-20220120_231123")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L7_ch004 = Exp_builder().set_basic("train", use_db_obj, block1_L7_ch004_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L7_ch004_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L7_ch004).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L7_ch004_block1_&&_I_to_Cy_L7_ch004_block1-20220120_210534")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L7_ch002 = Exp_builder().set_basic("train", use_db_obj, block1_L7_ch002_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L7_ch002_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L7_ch002).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L7_ch002_block1_&&_I_to_Cy_L7_ch002_block1-20220120_190235")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L7_ch001 = Exp_builder().set_basic("train", use_db_obj, block1_L7_ch001_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L7_ch001_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L7_ch001).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L7_ch001_block1_&&_I_to_Cy_L7_ch001_block1-20220121_044429")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)

L8_ch016 = Exp_builder().set_basic("train", use_db_obj, block1_L8_ch016_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L8_ch016_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L8_ch016).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L8_ch016_block1_&&_I_to_Cy_L8_ch016_block1-20220123_203804")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L8_ch008 = Exp_builder().set_basic("train", use_db_obj, block1_L8_ch008_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L8_ch008_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L8_ch008).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L8_ch008_block1_&&_I_to_Cy_L8_ch008_block1-20220123_152449")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L8_ch004 = Exp_builder().set_basic("train", use_db_obj, block1_L8_ch004_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L8_ch004_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L8_ch004).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L8_ch004_block1_&&_I_to_Cy_L8_ch004_block1-20220123_130543")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L8_ch002 = Exp_builder().set_basic("train", use_db_obj, block1_L8_ch002_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L8_ch002_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L8_ch002).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L8_ch002_block1_&&_I_to_Cy_L8_ch002_block1-20220123_105605")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L8_ch001 = Exp_builder().set_basic("train", use_db_obj, block1_L8_ch001_sig, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L8_ch001_sig.kong_model.model_describe) .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_exp_builder.L8_ch001).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L8_ch001_block1_&&_I_to_Cy_L8_ch001_block1-20220123_183359")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)

##############################################################################################################################################################################################################################################################################################################################################################################
L5_ch128_limit = Exp_builder().set_basic("train", use_db_obj, block1_L5_ch128_sig_limit, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L5_ch128_sig_limit.kong_model.model_describe + "_limit") .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_limit_exp_builder.L5_ch128_limit).set_result_name(result_name="")

L6_ch128_limit = Exp_builder().set_basic("train", use_db_obj, block1_L6_ch128_sig_limit, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L6_ch128_sig_limit.kong_model.model_describe + "_limit") .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_limit_exp_builder.L6_ch128_limit).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L6_ch128_block1_&&_I_to_Cy_L6_ch128_block1_limit-20220121_183539")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)

L7_ch128_limit = Exp_builder().set_basic("train", use_db_obj, block1_L7_ch128_sig_limit, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L7_ch128_sig_limit.kong_model.model_describe + "_limit") .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_limit_exp_builder.L7_ch128_limit).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L7_ch128_block1_&&_I_to_Cy_L7_ch128_block1_limit-20220121_195310")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L7_ch064_limit = Exp_builder().set_basic("train", use_db_obj, block1_L7_ch064_sig_limit, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L7_ch064_sig_limit.kong_model.model_describe + "_limit") .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_limit_exp_builder.L7_ch064_limit).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L7_ch064_block1_&&_I_to_Cy_L7_ch064_block1_limit-20220121_143406")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)

L8_ch128_limit = Exp_builder().set_basic("train", use_db_obj, block1_L8_ch128_sig_limit, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L8_ch128_sig_limit.kong_model.model_describe + "_limit") .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_limit_exp_builder.L8_ch128_limit).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L8_ch128_block1_&&_I_to_Cy_L8_ch128_block1_limit-20220123_212428")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L8_ch064_limit = Exp_builder().set_basic("train", use_db_obj, block1_L8_ch064_sig_limit, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L8_ch064_sig_limit.kong_model.model_describe + "_limit") .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_limit_exp_builder.L8_ch064_limit).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L8_ch064_block1_&&_I_to_Cy_L8_ch064_block1_limit-20220123_154728")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)
L8_ch032_limit = Exp_builder().set_basic("train", use_db_obj, block1_L8_ch032_sig_limit, use_loss_obj, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L8_ch032_sig_limit.kong_model.model_describe + "_limit") .set_train_args(epochs= 60).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_multi_model_reload_exp_builders_dict(I_to_Wx_Wy_Wz=Reload_from_which_Exp, W_to_Cx_Cy=W_to_Cxy_limit_exp_builder.L8_ch032_limit).set_result_name(result_name="I_to_Wx_Wy_Wz_I_to_Wx_L5_ch032_block1_&&_I_to_Wy_L5_ch032_block1_&&_I_to_Wz_L5_ch032_block1_&&_W_to_Cx_Cy_I_to_Cx_L8_ch032_block1_&&_I_to_Cy_L8_ch032_block1_limit-20220123_114028")  #.change_result_name_v4_Remove_sig_out(run_change=True, print_msg=True)  #.change_result_name_v3_to_v4_Remove_db_name(run_change=True, print_msg=True)


if(__name__ == "__main__"):
    print("build exps cost time:", time.time() - start_time)
    if len(sys.argv) < 2:
        ############################################################################################################
        ### 直接按 F5 或打 python step10_b1_exp_obj_load_and_train_and_test.py，後面沒有接東西喔！才不會跑到下面給 step10_b_subprocss.py 用的程式碼~~~
        L3_ch128.build().run()
        # print('no argument')
        sys.exit()

    ### 以下是給 step10_b_subprocess.py 用的，相當於cmd打 python step10_b1_exp_obj_load_and_train_and_test.py 某個exp.build().run()
    eval(sys.argv[1])
