# result_access_path = "D:/0 data_dir/"  ### 放所有training 且 後處理好的 result
result_read_path   = "D:/0 data_dir/"    ### 放所有training 且 後處理好的 result
result_write_path  = "G:/0 data_dir/"    ### 放所有training 且 後處理好的 result
# result_access_path = "G:/0 data_dir/"  ### 放 training 中的 result
# result_access_path = "I:/0 data_dir/"  ### 整理 舊analyze
JPG_QUALITY = 30
CORE_AMOUNT = 8
CORE_AMOUNT_NPY_TO_NPZ = 4
CORE_AMOUNT_BM_REC_VISUAL = 14
CORE_AMOUNT_SAVE_AS_JPG = 12         ### Save_as_jpg
CORE_AMOUNT_FIND_LTRD_AND_CROP = 12  ### Find_ltrd_and_crop