#############################################################################################################################################################################################################
#############################################################################################################################################################################################################
### 把 kong_model2 加入 sys.path
import os
code_exe_path = os.path.realpath(__file__)                   ### 目前執行 step10_b.py 的 path
code_exe_path_element = code_exe_path.split("\\")            ### 把 path 切分 等等 要找出 kong_model 在第幾層
kong_layer = code_exe_path_element.index("kong_model2")      ### 找出 kong_model2 在第幾層
kong_model2_dir = "\\".join(code_exe_path_element[:kong_layer + 1])  ### 定位出 kong_model2 的 dir
import sys                                                   ### 把 kong_model2 加入 sys.path
sys.path.append(kong_model2_dir)
# print(__file__.split("\\")[-1])
# print("    code_exe_path:", code_exe_path)
# print("    code_exe_path_element:", code_exe_path_element)
# print("    kong_layer:", kong_layer)
# print("    kong_model2_dir:", kong_model2_dir)
#############################################################################################################################################################################################################
kong_to_py_layer = len(code_exe_path_element) - 1 - kong_layer  ### 中間 -1 是為了長度轉index
# print("    kong_to_py_layer:", kong_to_py_layer)
if  (kong_to_py_layer == 0): template_dir = ""
elif(kong_to_py_layer == 2): template_dir = code_exe_path_element[kong_layer + 1][7:]  ### [7:] 是為了去掉 step1x_
elif(kong_to_py_layer == 3): template_dir = code_exe_path_element[kong_layer + 1][7:] + "/" + code_exe_path_element[kong_layer + 2][5:]  ### [5:] 是為了去掉 mask_ ，前面的 mask_ 是為了python 的 module 不能 數字開頭， 隨便加的這樣子
elif(kong_to_py_layer >  3): template_dir = code_exe_path_element[kong_layer + 1][7:] + "/" + code_exe_path_element[kong_layer + 2][5:] + "/" + "/".join(code_exe_path_element[kong_layer + 3: -1])  ### 前面的 mask_ 是為了python 的 module 不能 數字開頭， 隨便加的這樣子
# print("    template_dir:", template_dir)  ### 舉例： template_dir: 7_mask_unet/5_os_book_and_paper_have_dtd_hdr_mix_bg_tv_s04_mae
#############################################################################################################################################################################################################
exp_dir = template_dir
#############################################################################################################################################################################################################
from step06_a_datas_obj import *
from step09_e5_flow_unet2_obj_I_to_M import *
from step10_a2_loss_info_obj import *
from step10_b2_exp_builder import Exp_builder
#############################################################################################################################################################################################################
'''
exp_dir 是 決定 result_dir 的 "上一層"資料夾 名字喔！ exp_dir要巢狀也沒問題～
比如：exp_dir = "7_block1/自己命的名字"，那 result_dir 就都在：
    7_block1/自己命的名字/result_a
    7_block1/自己命的名字/result_b
    7_block1/自己命的名字/...
'''

use_db_obj = type9_mask_flow_have_bg_dtd_hdr_mix_and_paper
#################################################################################################################################################################################################################################################################################################################################################################################################
#################################################################################################################################################################################################################################################################################################################################################################################################
L2_ch128 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L2_ch128_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L2_ch128_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="")
L2_ch064 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L2_ch064_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L2_ch064_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="")
L2_ch032 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L2_ch032_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L2_ch032_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="")
L2_ch016 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L2_ch016_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L2_ch016_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="")
L2_ch008 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L2_ch008_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L2_ch008_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="")
L2_ch004 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L2_ch004_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L2_ch004_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="")
L2_ch002 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L2_ch002_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L2_ch002_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="")
L2_ch001 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L2_ch001_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L2_ch001_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="")
########################################################################################################################################################################################################################################################################################################################################################################################
L3_ch128 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L3_ch128_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L3_ch128_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L3_ch128_block1_sig_out_1-20211211_104042")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L3_ch064 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L3_ch064_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L3_ch064_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L3_ch064_block1_sig_out_1-20211211_125010")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L3_ch032 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L3_ch032_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L3_ch032_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L3_ch032_block1_sig_out_1-20211211_134329")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L3_ch016 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L3_ch016_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L3_ch016_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L3_ch016_block1_sig_out_1-20211211_141609")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L3_ch008 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L3_ch008_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L3_ch008_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L3_ch008_block1_sig_out_1-20211211_144631")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L3_ch004 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L3_ch004_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L3_ch004_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L3_ch004_block1_sig_out_1-20211211_151607")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L3_ch002 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L3_ch002_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L3_ch002_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L3_ch002_block1_sig_out_1-20211211_154514")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L3_ch001 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L3_ch001_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L3_ch001_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L3_ch001_block1_sig_out_1-20211211_161421")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
########################################################################################################################################################################################################################################################################################################################################################################################
L4_ch128 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L4_ch128_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L4_ch128_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L4_ch128_block1_sig_out_1-20211211_164326")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L4_ch064 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L4_ch064_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L4_ch064_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L4_ch064_block1_sig_out_1-20211211_223749")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L4_ch032 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L4_ch032_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L4_ch032_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L4_ch032_block1_sig_out_1-20211211_234618")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L4_ch016 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L4_ch016_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L4_ch016_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L4_ch016_block1_sig_out_1-20211212_002019")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L4_ch008 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L4_ch008_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L4_ch008_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L4_ch008_block1_sig_out_1-20211212_005110")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L4_ch004 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L4_ch004_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L4_ch004_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L4_ch004_block1_sig_out_1-20211212_012104")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L4_ch002 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L4_ch002_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L4_ch002_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L4_ch002_block1_sig_out_1-20211212_015025")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L4_ch001 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L4_ch001_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L4_ch001_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L4_ch001_block1_sig_out_1-20211212_021939")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
########################################################################################################################################################################################################################################################################################################################################################################################
L5_ch128 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L5_ch128_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L5_ch128_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L5_ch128_block1_sig_out_1-20211211_231704")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L5_ch064 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L5_ch064_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L5_ch064_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L5_ch064_block1_sig_out_1-20211212_075820")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L5_ch032 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L5_ch032_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L5_ch032_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L5_ch032_block1_sig_out_1-20211211_193544")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L5_ch016 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L5_ch016_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L5_ch016_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L5_ch016_block1_sig_out_1-20211211_202516")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L5_ch008 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L5_ch008_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L5_ch008_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L5_ch008_block1_sig_out_1-20211211_205858")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L5_ch004 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L5_ch004_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L5_ch004_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L5_ch004_block1_sig_out_1-20211211_213053")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L5_ch002 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L5_ch002_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L5_ch002_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L5_ch002_block1_sig_out_1-20211211_220204")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L5_ch001 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L5_ch001_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L5_ch001_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L5_ch001_block1_sig_out_1-20211211_223305")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
########################################################################################################################################################################################################################################################################################################################################################################################
L6_ch064 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L6_ch064_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L6_ch064_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L6_ch064_block1_sig_out_1-20211212_032202")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L6_ch032 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L6_ch032_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L6_ch032_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L6_ch032_block1_sig_out_1-20211212_102301")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L6_ch016 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L6_ch016_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L6_ch016_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L6_ch016_block1_sig_out_1-20211212_122012")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L6_ch008 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L6_ch008_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L6_ch008_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L6_ch008_block1_sig_out_1-20211212_125539")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L6_ch004 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L6_ch004_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L6_ch004_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L6_ch004_block1_sig_out_1-20211212_132723")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L6_ch002 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L6_ch002_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L6_ch002_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L6_ch002_block1_sig_out_1-20211212_135729")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L6_ch001 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L6_ch001_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L6_ch001_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L6_ch001_block1_sig_out_1-20211212_141719")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
########################################################################################################################################################################################################################################################################################################################################################################################
L7_ch032 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L7_ch032_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L7_ch032_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L7_ch032_block1_sig_out_1-20211212_015703")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L7_ch016 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L7_ch016_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L7_ch016_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L7_ch016_block1_sig_out_1-20211212_064056")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L7_ch008 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L7_ch008_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L7_ch008_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L7_ch008_block1_sig_out_1-20211212_082523")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L7_ch004 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L7_ch004_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L7_ch004_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L7_ch004_block1_sig_out_1-20211212_083127")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L7_ch002 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L7_ch002_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L7_ch002_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L7_ch002_block1_sig_out_1-20211212_090443")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L7_ch001 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L7_ch001_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L7_ch001_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L7_ch001_block1_sig_out_1-20211212_093732")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
########################################################################################################################################################################################################################################################################################################################################################################################
L8_ch016 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L8_ch016_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L8_ch016_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L8_ch016_block1_sig_out_1-20211212_174844")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L8_ch008 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L8_ch008_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L8_ch008_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L8_ch008_block1_sig_out_1-20211212_215801")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L8_ch004 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L8_ch004_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L8_ch004_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L8_ch004_block1_sig_out_1-20211212_233052")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L8_ch002 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L8_ch002_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L8_ch002_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L8_ch002_block1_sig_out_1-20211213_000532")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
L8_ch001 = Exp_builder().set_basic("test_real_photo_paper2", use_db_obj, block1_L8_ch001_sig, G_mae_s001_loss_info_builder, exp_dir=exp_dir, code_exe_path=code_exe_path, describe_end=block1_L8_ch001_sig.kong_model.model_describe).set_train_args(epochs= 60, exp_bn_see_arg=None).set_train_in_gt_use_range(use_in_range=Range(0, 1), use_gt_range=Range(0, 1)).set_result_name(result_name="type8_blender-L8_ch001_block1_sig_out_1-20211213_003838")  #.change_result_name_v2_Remove_os_book(run_change=False).change_result_name_v2_Describe_end_use_New_Describe_end(run_change=False).change_result_name_v2_to_v3_Remove_describe_mid_model_name(run_change=False, print_msg=True)
#################################################################################################################################################################################################################################################################################################################################################################################################
#################################################################################################################################################################################################################################################################################################################################################################################################

if(__name__ == "__main__"):
    print("build exps cost time:", time.time() - start_time)
    if len(sys.argv) < 2:
        ############################################################################################################
        ### 直接按 F5 或打 python step10_b1_exp_obj_load_and_train_and_test.py，後面沒有接東西喔！才不會跑到下面給 step10_b_subprocss.py 用的程式碼~~~
        # L8_ch001.build().run()
        # L2_ch001.build().run()
        L3_ch008.build().run()
        # print('no argument')
        sys.exit()

    ### 以下是給 step10_b_subprocess.py 用的，相當於cmd打 python step10_b1_exp_obj_load_and_train_and_test.py 某個exp.build().run()
    eval(sys.argv[1])
